services:
  inventory-app:
    build: .
    container_name: inventory_system
    restart: always
    environment:
      - GOOGLE_SCRIPT_URL=process.env.GOOGLE_SCRIPT_URL
    ports:
      - "3000:3000"